In [139]:
import pandas as pd
import numpy as np

In [140]:
df = pd.read_csv('/content/Daily Household Transactions.csv')

In [141]:
df.head()

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
0,20/09/2018 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR
1,20/09/2018 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR
2,19/09/2018,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
4,16/09/2018 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2461 entries, 0 to 2460
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2461 non-null   object
 1   Mode            2461 non-null   object
 2   Category        2461 non-null   object
 3   Subcategory     1826 non-null   object
 4   Note            1940 non-null   object
 5   Amount          2461 non-null   float64
 6   Income/Expense  2461 non-null   object
 7   Currency        2461 non-null   object
dtypes: float64(1), object(7)
memory usage: 153.9+ KB

In [143]:
df.isnull().sum()

Date                0
Mode                0
Category            0
Subcategory       635
Note              521
Amount              0
Income/Expense      0
Currency            0
dtype: int64

# **Unique Values To Know More About Data**

In [144]:
df['Subcategory'].unique()

array(['Train', 'snacks', 'Netflix', 'Mobile Service Provider',
       'Ganesh Pujan', 'Tata Sky', 'auto', nan, 'Grocery', 'Lunch',
       'Milk', 'Pocket money', 'Laundry', 'breakfast', 'Dinner', 'Sweets',
       'Kirana', 'Ice cream', 'curd', 'Biscuits', 'Rajgira ladu',
       'Navratri', 'train', 'Tea', 'flour mill', 'Appliances',
       'home decor', 'grooming', 'Health', 'Clothing', 'clothes', 'Home',
       'chocolate', 'Medicine', 'Eating out', 'Movie', 'vegetables',
       'fruits', 'Potato', 'Onions', 'Taxi', 'Hardware', 'Eggs', 'Bread',
       'Petrol', 'Hospital', 'Mahanagar Gas', 'Lab Tests', 'Bus',
       'Travels', 'Kitchen', 'Footwear', 'Entry Fees', 'gadgets',
       'Accessories', 'misc', 'Stationary', 'Newspaper', 'Toiletries',
       'Bike', 'beverage', 'makeup', 'Books', 'Holi', 'Courier',
       'Leisure', 'Updation', 'Amazon Prime', 'Edtech Course', 'Hotstar',
       'Diwali', 'Wifi Internet Service', 'Trip', 'Furniture', 'Water',
       'Cable TV', 'medicine', 'Mutual fund', 'Public Provident Fund',
       'ropeway', 'RD', 'LIC', 'Saloon', 'gift', 'Rakshabandhan',
       'exam fee', 'Kindle unlimited', 'OTT Platform', 'School supplies',
       'Audible', 'Makeup'], dtype=object)

In [145]:
df['Category'].unique()

array(['Transportation', 'Food', 'subscription', 'Festivals', 'Other',
       'Small Cap fund 2', 'Small cap fund 1', 'Family',
       'Equity Mutual Fund E', 'Apparel', 'Public Provident Fund',
       'Saving Bank account 1', 'Gift', 'Salary', 'Household',
       'Dividend earned on Shares', 'Interest', 'Life Insurance',
       'Beauty', 'Health', 'Money transfer', 'maid', 'Culture',
       'Tax refund', 'Tourism', 'Share Market', 'Self-development',
       'Amazon pay cashback', 'Education', 'scrap', 'Petty cash',
       'Documents', 'Gpay Reward', 'Social Life', 'Equity Mutual Fund A',
       'Maturity amount', 'Fixed Deposit', 'Equity Mutual Fund C',
       'Equity Mutual Fund F', 'Recurring Deposit',
       'Saving Bank account 2', 'Equity Mutual Fund D',
       'Equity Mutual Fund B', 'Bonus', 'Investment', 'Grooming', 'Rent',
       'Cook', 'garbage disposal', 'water (jar /tanker)'], dtype=object)

In [146]:
# Transportation, Food,

In [147]:
df['Mode'].unique()

array(['Cash', 'Saving Bank account 1', 'Credit Card',
       'Equity Mutual Fund B', 'Debit Card', 'Share Market Trading',
       'Saving Bank account 2', 'Equity Mutual Fund C',
       'Equity Mutual Fund A', 'Equity Mutual Fund D', 'Fixed Deposit',
       'Recurring Deposit'], dtype=object)

In [148]:
df['Income/Expense'].unique()

array(['Expense', 'Transfer-Out', 'Income'], dtype=object)

In [149]:
df['Currency'].unique()

array(['INR'], dtype=object)

In [150]:
df[df['Note'].isnull()]

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
10,13/09/2018,Saving Bank account 1,Small Cap fund 2,NaN,NaN,5000.0,Transfer-Out,INR
11,13/09/2018,Saving Bank account 1,Small cap fund 1,NaN,NaN,5000.0,Transfer-Out,INR
17,8/9/2018,Cash,Family,Pocket money,NaN,40.0,Expense,INR
19,7/9/2018,Saving Bank account 1,Equity Mutual Fund E,NaN,NaN,1000.0,Transfer-Out,INR
27,3/9/2018,Cash,Family,Pocket money,NaN,2000.0,Expense,INR
...,...,...,...,...,...,...,...,...
2318,28/02/2015 11:33:42,Cash,Food,Milk,NaN,26.0,Expense,INR
2320,28/02/2015 17:48:39,Cash,Food,Tea,NaN,20.0,Expense,INR
2321,26/02/2015 20:06:17,Cash,Food,Tea,NaN,6.0,Expense,INR
2324,26/02/2015 20:05:31,Cash,Food,Milk,NaN,26.0,Expense,INR
2327,24/02/2015 05:46:53,Cash,Food,Tea,NaN,10.0,Expense,INR

In [151]:
df['Date'].unique()

array(['20/09/2018 12:04:08', '20/09/2018 12:03:15', '19/09/2018', ...,
       '3/1/2015', '2/1/2015', '1/1/2015'], dtype=object)

---------------------------

#***Sum When Mode = 'Cash'***

In [152]:
Cash_sum = df[df['Mode']=='Cash'].Amount

In [153]:
Cash_sum.sum()

np.float64(176252.0)

In [154]:
df[df['Category']=='subscription'].Subcategory.unique()

array(['Netflix', 'Mobile Service Provider', 'Tata Sky', 'Mahanagar Gas',
       'Newspaper', 'Amazon Prime', 'Edtech Course', 'Hotstar',
       'Wifi Internet Service', 'Cable TV', 'Kindle unlimited',
       'OTT Platform', 'Audible'], dtype=object)

The persons Subscriptions Consists of:

'Netflix', 'Mobile Service Provider', 'Tata Sky', 'Mahanagar Gas',
       'Newspaper', 'Amazon Prime', 'Edtech Course', 'Hotstar',
       'Wifi Internet Service', 'Cable TV', 'Kindle unlimited',
       'OTT Platform', 'Audible

In [155]:
# Sum of Subscription

In [156]:
subscription = df[df['Category']=='subscription']

In [157]:
subscription['Amount'].sum()

np.float64(114587.90999999999)

In [158]:
List = subscription['Subcategory'].unique()
for i in List:
  df1 = df[df['Subcategory']==i]
  print(df1['Subcategory'].unique())
  print(df1['Amount'].sum())

['Netflix']
1492.0
['Mobile Service Provider']
26650.0
['Tata Sky']
4066.0
['Mahanagar Gas']
2208.0
['Newspaper']
3101.0
['Amazon Prime']
1477.0
['Edtech Course']
63733.41999999999
['Hotstar']
1243.49
['Wifi Internet Service']
8460.0
['Cable TV']
783.0
['Kindle unlimited']
676.0
['OTT Platform']
300.0
['Audible']
398.0

In [159]:
result_df = (
    df[df['Subcategory'].isin(subscription['Subcategory'].unique())]
    .groupby('Subcategory', as_index=False)['Amount']
    .sum()
    .rename(columns={'Amount': 'Total Amount'})
)

print(result_df)

                Subcategory  Total Amount
0              Amazon Prime       1477.00
1                   Audible        398.00
2                  Cable TV        783.00
3             Edtech Course      63733.42
4                   Hotstar       1243.49
5          Kindle unlimited        676.00
6             Mahanagar Gas       2208.00
7   Mobile Service Provider      26650.00
8                   Netflix       1492.00
9                 Newspaper       3101.00
10             OTT Platform        300.00
11                 Tata Sky       4066.00
12    Wifi Internet Service       8460.00

In [160]:
df[df['Subcategory']=='Edtech Course']

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
706,20/12/2017 10:31:16,Credit Card,subscription,Edtech Course,Renewal,28400.00,Expense,INR
743,5/12/2017,Saving Bank account 1,subscription,Edtech Course,NaN,2700.00,Expense,INR
862,3/11/2017,Saving Bank account 1,subscription,Edtech Course,NaN,2700.00,Expense,INR
915,4/10/2017,Saving Bank account 1,subscription,Edtech Course,NaN,2700.00,Expense,INR
998,5/9/2017,Saving Bank account 1,subscription,Edtech Course,NaN,2700.00,Expense,INR
1103,2/8/2017,Saving Bank account 1,subscription,Edtech Course,NaN,2700.00,Expense,INR
1200,4/7/2017,Saving Bank account 1,subscription,Edtech Course,NaN,2700.00,Expense,INR
1283,3/6/2017,Saving Bank account 1,subscription,Edtech Course,NaN,2700.10,Expense,INR
1405,3/5/2017,Saving Bank account 1,subscription,Edtech Course,NaN,2700.10,Expense,INR
1464,3/4/2017,Saving Bank account 1,subscription,Edtech Course,NaN,2700.10,Expense,INR
1543,7/3/2017,Saving Bank account 1,subscription,Edtech Course,NaN,2700.10,Expense,INR
1634,3/2/2017,Saving Bank account 1,subscription,Edtech Course,NaN,2700.10,Expense,INR
1689,3/1/2017,Saving Bank account 1,subscription,Edtech Course,NaN,2816.92,Expense,INR
1718,31/12/2016 13:47:26,Cash,subscription,Edtech Course,EMI 1,2816.00,Expense,INR

In [161]:
df[df['Subcategory']=='Mobile Service Provider']

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
12,12/9/2018,Credit Card,subscription,Mobile Service Provider,Data booster pack,667.0,Expense,INR
232,23/06/2018 19:25:22,Credit Card,subscription,Mobile Service Provider,Annual recharge,2545.0,Expense,INR
234,22/06/2018 15:32:22,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,181.0,Expense,INR
236,19/06/2018 10:25:47,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,25.0,Expense,INR
...,...,...,...,...,...,...,...,...
2005,15/03/2016 17:08:31,Saving Bank account 1,subscription,Mobile Service Provider,Mobile Service Provider recharge wfh,251.0,Expense,INR
2012,6/3/2016,Saving Bank account 1,subscription,Mobile Service Provider,Mobile Service Provider recharge wfh,251.0,Expense,INR
2020,27/02/2016 07:49:16,Saving Bank account 1,subscription,Mobile Service Provider,Mobile Service Provider recharge wfh,251.0,Expense,INR
2035,8/2/2016,Saving Bank account 1,subscription,Mobile Service Provider,Mobile Service Provider recharge wfh,251.0,Expense,INR
2049,9/1/2016,Saving Bank account 1,subscription,Mobile Service Provider,Mobile Service Provider recharge wfh,251.0,Expense,INR

In [162]:
df[df['Subcategory']=='Wifi Internet Service']

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
908,9/10/2017,Saving Bank account 1,subscription,Wifi Internet Service,1 Year Plan (40mbps + UL+ 3 Months Free),5640.0,Expense,INR
1510,16/03/2017 20:39:13,Saving Bank account 1,subscription,Wifi Internet Service,6 months ( 30mb UL plan + 1 month free),2820.0,Expense,INR

Noticed there is some mistake in date..
where when im asking for max in date its giving 2017, but actually the most recent date was 20/09/2018...


so i came up with solution of seperating date and timetsamps in different column

In [163]:
df['Date'].max()

'9/9/2017'

In [164]:
df['Date'].min()

'1/1/2015'

In [165]:
df

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
0,20/09/2018 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR
1,20/09/2018 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR
2,19/09/2018,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
4,16/09/2018 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR
...,...,...,...,...,...,...,...,...
2456,1/1/2015,Cash,Transportation,NaN,share jeep - Place T base to top,20.0,Expense,INR
2457,1/1/2015,Cash,Transportation,NaN,share auto - Place H to Place T base,20.0,Expense,INR
2458,1/1/2015,Cash,Transportation,NaN,bus - brc to Place H,30.0,Expense,INR
2459,1/1/2015,Cash,Food,NaN,tea,10.0,Expense,INR
2460,1/1/2015,Cash,Transportation,NaN,share auto - hospital to brc station,10.0,Expense,INR

In [166]:
df.head()

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
0,20/09/2018 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR
1,20/09/2018 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR
2,19/09/2018,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
4,16/09/2018 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR

In [167]:
# Split into date and time (if time exists)
df[['Only_Date', 'Time']] = df['Date'].str.split(' ', n=1, expand=True)

# Convert the date column to datetime
df['Only_Date'] = pd.to_datetime(df['Only_Date'], format='%d/%m/%Y')

# Convert the time column to time
df['Time'] = pd.to_datetime(df['Time'], format='%H:%M:%S', errors='coerce').dt.time

In [168]:
df.head()

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency,Only_Date,Time
0,20/09/2018 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR,2018-09-20,12:04:08
1,20/09/2018 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR,2018-09-20,12:03:15
2,19/09/2018,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR,2018-09-19,NaT
3,17/09/2018 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR,2018-09-17,23:41:17
4,16/09/2018 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR,2018-09-16,17:15:08

In [169]:
df = df.drop(columns=['Date','Currency'])

In [170]:
df

,Mode,Category,Subcategory,Note,Amount,Income/Expense,Only_Date,Time
0,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,2018-09-20,12:04:08
1,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,2018-09-20,12:03:15
2,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,2018-09-19,NaT
3,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,2018-09-17,23:41:17
4,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,2018-09-16,17:15:08
...,...,...,...,...,...,...,...,...
2456,Cash,Transportation,NaN,share jeep - Place T base to top,20.0,Expense,2015-01-01,NaT
2457,Cash,Transportation,NaN,share auto - Place H to Place T base,20.0,Expense,2015-01-01,NaT
2458,Cash,Transportation,NaN,bus - brc to Place H,30.0,Expense,2015-01-01,NaT
2459,Cash,Food,NaN,tea,10.0,Expense,2015-01-01,NaT
2460,Cash,Transportation,NaN,share auto - hospital to brc station,10.0,Expense,2015-01-01,NaT

In [171]:
df.rename(columns={'Only_Date':'Date'}, inplace=True)

In [172]:
df

,Mode,Category,Subcategory,Note,Amount,Income/Expense,Date,Time
0,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,2018-09-20,12:04:08
1,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,2018-09-20,12:03:15
2,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,2018-09-19,NaT
3,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,2018-09-17,23:41:17
4,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,2018-09-16,17:15:08
...,...,...,...,...,...,...,...,...
2456,Cash,Transportation,NaN,share jeep - Place T base to top,20.0,Expense,2015-01-01,NaT
2457,Cash,Transportation,NaN,share auto - Place H to Place T base,20.0,Expense,2015-01-01,NaT
2458,Cash,Transportation,NaN,bus - brc to Place H,30.0,Expense,2015-01-01,NaT
2459,Cash,Food,NaN,tea,10.0,Expense,2015-01-01,NaT
2460,Cash,Transportation,NaN,share auto - hospital to brc station,10.0,Expense,2015-01-01,NaT

Now you can see, it it showing right date...

In [173]:
df['Date'].max()

Timestamp('2018-09-20 00:00:00')

In [174]:
df['Date'].min()

Timestamp('2015-01-01 00:00:00')

In [175]:
df.isnull().sum()

Mode                 0
Category             0
Subcategory        635
Note               521
Amount               0
Income/Expense       0
Date                 0
Time              1158
dtype: int64

In [176]:
df['Subcategory'] = df['Subcategory'].fillna('Unknown')

In [177]:
df.isnull().sum()

Mode                 0
Category             0
Subcategory          0
Note               521
Amount               0
Income/Expense       0
Date                 0
Time              1158
dtype: int64

In [178]:
duplicates = df.duplicated().sum()

print("Duplicate Rows :", duplicates)

Duplicate Rows : 9

In [179]:
df[df.duplicated(keep=False)]

,Mode,Category,Subcategory,Note,Amount,Income/Expense,Date,Time
767,Saving Bank account 1,Recurring Deposit,Unknown,NaN,1000.0,Transfer-Out,2017-12-01,NaT
768,Saving Bank account 1,Recurring Deposit,Unknown,NaN,1000.0,Transfer-Out,2017-12-01,NaT
867,Saving Bank account 1,Recurring Deposit,Unknown,NaN,1000.0,Transfer-Out,2017-11-01,NaT
868,Saving Bank account 1,Recurring Deposit,Unknown,NaN,1000.0,Transfer-Out,2017-11-01,NaT
921,Saving Bank account 1,Recurring Deposit,Unknown,NaN,1000.0,Transfer-Out,2017-10-01,NaT
922,Saving Bank account 1,Recurring Deposit,Unknown,NaN,1000.0,Transfer-Out,2017-10-01,NaT
1006,Saving Bank account 1,Recurring Deposit,Unknown,NaN,1000.0,Transfer-Out,2017-09-01,NaT
1007,Saving Bank account 1,Recurring Deposit,Unknown,NaN,1000.0,Transfer-Out,2017-09-01,NaT
1108,Saving Bank account 1,Recurring Deposit,Unknown,NaN,1000.0,Transfer-Out,2017-08-01,NaT
1109,Saving Bank account 1,Recurring Deposit,Unknown,NaN,1000.0,Transfer-Out,2017-08-01,NaT
1209,Saving Bank account 1,Recurring Deposit,Unknown,NaN,1000.0,Transfer-Out,2017-07-01,NaT
1210,Saving Bank account 1,Recurring Deposit,Unknown,NaN,1000.0,Transfer-Out,2017-07-01,NaT
1360,Cash,Food,Tea,NaN,10.0,Expense,2017-05-12,NaT
1362,Cash,Food,Tea,NaN,10.0,Expense,2017-05-12,NaT
1815,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,2016-11-10,NaT
1816,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,2016-11-10,NaT
1853,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,2016-10-10,NaT
1854,Saving Bank account 1,Investment,Mutual fund,NaN,1000.0,Expense,2016-10-10,NaT

In [180]:
df = df.drop_duplicates()

In [181]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [Mode, Category, Subcategory, Note, Amount, Income/Expense, Date, Time]
Index: []

In [182]:
df['Year'] = df['Date'].dt.year
df['Month Name'] = df['Date'].dt.month_name()
df['Quarter'] = df['Date'].dt.quarter

/tmp/ipykernel_3618/3497792754.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Year'] = df['Date'].dt.year
/tmp/ipykernel_3618/3497792754.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Month Name'] = df['Date'].dt.month_name()
/tmp/ipykernel_3618/3497792754.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Quarter'] = df['Date'].dt.quarter

In [183]:
df

,Mode,Category,Subcategory,Note,Amount,Income/Expense,Date,Time,Year,Month Name,Quarter
0,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,2018-09-20,12:04:08,2018,September,3
1,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,2018-09-20,12:03:15,2018,September,3
2,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,2018-09-19,NaT,2018,September,3
3,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,2018-09-17,23:41:17,2018,September,3
4,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,2018-09-16,17:15:08,2018,September,3
...,...,...,...,...,...,...,...,...,...,...,...
2456,Cash,Transportation,Unknown,share jeep - Place T base to top,20.0,Expense,2015-01-01,NaT,2015,January,1
2457,Cash,Transportation,Unknown,share auto - Place H to Place T base,20.0,Expense,2015-01-01,NaT,2015,January,1
2458,Cash,Transportation,Unknown,bus - brc to Place H,30.0,Expense,2015-01-01,NaT,2015,January,1
2459,Cash,Food,Unknown,tea,10.0,Expense,2015-01-01,NaT,2015,January,1
2460,Cash,Transportation,Unknown,share auto - hospital to brc station,10.0,Expense,2015-01-01,NaT,2015,January,1

In [184]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2452 entries, 0 to 2460
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Mode            2452 non-null   object
 1   Category        2452 non-null   object
 2   Subcategory     2452 non-null   object
 3   Note            1940 non-null   object
 4   Amount          2452 non-null   float64
 5   Income/Expense  2452 non-null   object
 6   Date            2452 non-null   datetime64[ns]
 7   Time            1303 non-null   object
 8   Year            2452 non-null   int32
 9   Month Name      2452 non-null   object
 10  Quarter         2452 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(2), object(7)
memory usage: 210.7+ KB

In [185]:
df['Income/Expense'].unique()

array(['Expense', 'Transfer-Out', 'Income'], dtype=object)

In [186]:
income = df[df['Income/Expense']=='Income']['Amount'].sum()

print(income)

3042397.3499999996

In [187]:
expense = df[df['Income/Expense']=='Expense']['Amount'].sum()

print(expense)

1955380.5300000003

In [188]:
net_savings = income - expense

In [189]:
net_savings_rate = (net_savings/income)*100
print(net_savings_rate)

35.72895631137726

In [190]:
expense_category = df[df['Income/Expense']=='Expense'].groupby('Category')['Amount'].sum().sort_values(ascending=False)

In [191]:
expense_category

Category
Money transfer           606528.90
Investment               269858.00
Transportation           169053.78
Household                161645.58
subscription             114587.91
Food                      96393.10
Public Provident Fund     90000.00
Other                     87025.28
Family                    78582.20
Health                    66252.75
Tourism                   63608.85
Gift                      40168.00
Apparel                   25373.82
Recurring Deposit         22000.00
maid                      21839.00
Cook                      12443.00
Rent                      10709.00
Festivals                  6911.00
Culture                    4304.36
Beauty                     4189.00
Self-development           2357.00
Education                   537.00
Grooming                    400.00
Social Life                 298.00
water (jar /tanker)         148.00
Documents                   100.00
garbage disposal             67.00
Name: Amount, dtype: float64

In [192]:
expense_subcategory = df[df['Income/Expense']=='Expense'].groupby('Subcategory')['Amount'].sum().sort_values(ascending=False)

In [193]:
expense_subcategory.head(15), expense_subcategory.tail(15)

(Subcategory
 Unknown                    701672.28
 Home                       204505.90
 Public Provident Fund      150000.00
 Bike                        94593.00
 Appliances                  82081.00
 Mutual fund                 64000.00
 Edtech Course               63733.42
 Trip                        63300.00
 Pocket money                58195.00
 Kirana                      39147.58
 LIC                         33858.00
 Travels                     32338.98
 Health                      31497.75
 Mobile Service Provider     26650.00
 Dinner                      22903.10
 Name: Amount, dtype: float64,
 Subcategory
 Entry Fees         308.85
 medicine           300.00
 OTT Platform       300.00
 Leisure            298.00
 Water              205.00
 Rajgira ladu       190.00
 Onions             176.00
 curd               170.00
 chocolate          102.00
 Books              100.00
 Potato              93.00
 Updation            50.00
 Courier             50.00
 Holi                20.00
 School supplies     20.00
 Name: Amount, dtype: float64)

Here the Problem is Huge Amount is Subcategorized as Unknown... which is a problem i feel , will decode that later inthird round of cleaning

In [194]:
monthly_expense = (
    df[df['Income/Expense']=='Expense']
    .groupby(['Year','Month Name'])['Amount']
    .sum()
)

monthly_expense

Year  Month Name
2015  April          24222.00
      August         43340.00
      December       72030.00
      February       24308.00
      January        33870.00
      July           31735.00
      June           19567.00
      March          32631.40
      May            63118.00
      November       26459.00
      October        32217.00
      September      18577.00
2016  April          28460.00
      August         46502.00
      December       74916.60
      February       27021.00
      January        38435.00
      July           36462.00
      June           32013.90
      March          16631.00
      May            38309.00
      November       69175.00
      October        31138.20
      September      29020.50
2017  April          23834.38
      August        101393.70
      December       46805.00
      February       43943.35
      January       117797.42
      July           63873.00
      June           32293.55
      March          36502.08
      May            43830.10
      November       64364.00
      October        45532.09
      September      32419.00
2018  April          48339.58
      August         21305.65
      February       26218.00
      January       142080.90
      July           67738.36
      June           38161.02
      March          23396.75
      May            40670.00
      September       4724.00
Name: Amount, dtype: float64

In [195]:
monthly_income = (
    df[df['Income/Expense']=='Income']
    .groupby(['Year','Month Name'])['Amount']
    .sum()
)

monthly_income

Year  Month Name
2015  April          49306.00
      August         49806.00
      December       77335.00
      February       49806.00
      July           47859.00
      June           47859.00
      March          70806.00
      May            47859.00
      November       51306.00
      October        49806.00
      September      54606.00
2016  April          51562.45
      August         63894.00
      December       56590.00
      February       49806.00
      January        94806.00
      July           51556.00
      June           52284.00
      March          70806.00
      May            51556.00
      November       58096.00
      October        56647.00
      September      58893.00
2017  April          56957.00
      August        123383.00
      December       82321.00
      February       56021.00
      January        63101.00
      July          181617.00
      June           57827.00
      March          56686.00
      May            56970.00
      November      143155.00
      October         6000.00
      September      62373.00
2018  April          65824.15
      August         71735.75
      February       64738.00
      January       292938.00
      July           77267.50
      June           68551.00
      March          69343.50
      May            69238.00
      September       3500.00
Name: Amount, dtype: float64

In [196]:
payment = (
    df[df['Income/Expense']=='Expense']
    .groupby('Mode')['Amount']
    .sum()
    .sort_values(ascending=False)
)

payment

Mode
Saving Bank account 1    1575728.46
Credit Card               205254.01
Cash                      173421.00
Debit Card                   942.36
Saving Bank account 2         34.70
Name: Amount, dtype: float64

In [197]:
df['Amount'].mean()

np.float64(2757.9766639477975)

In [198]:
df[df['Income/Expense']=='Expense'].nlargest(10,'Amount')

,Mode,Category,Subcategory,Note,Amount,Income/Expense,Date,Time,Year,Month Name,Quarter
1710,Saving Bank account 1,Money transfer,Unknown,NaN,100000.0,Expense,2017-01-01,NaT,2017,January,1
608,Saving Bank account 1,Transportation,Bike,Two Wheeler Bikedelux second installment,50000.0,Expense,2018-01-18,21:57:46,2018,January,1
2086,Saving Bank account 1,Money transfer,Unknown,NaN,50000.0,Expense,2015-12-01,NaT,2015,December,4
582,Saving Bank account 1,Transportation,Bike,Two Wheeler Bikedelux third installment,43000.0,Expense,2018-01-27,18:15:53,2018,January,1
1080,Saving Bank account 1,Tourism,Trip,Tours and Travel,43000.0,Expense,2017-08-08,NaT,2017,August,3
1772,Saving Bank account 1,Investment,Public Provident Fund,NaN,40000.0,Expense,2016-12-01,NaT,2016,December,4
102,Saving Bank account 1,Money transfer,Home,NaN,30000.0,Expense,2018-07-31,18:01:20,2018,July,3
672,Saving Bank account 1,Money transfer,Home,NaN,30000.0,Expense,2018-01-01,NaT,2018,January,1
706,Credit Card,subscription,Edtech Course,Renewal,28400.0,Expense,2017-12-20,10:31:16,2017,December,4
376,Saving Bank account 1,Money transfer,Home,NaN,24500.0,Expense,2018-04-06,NaT,2018,April,2

In [199]:
df[df['Income/Expense']=='Income'].nlargest(10,'Amount')

,Mode,Category,Subcategory,Note,Amount,Income/Expense,Date,Time,Year,Month Name,Quarter
660,Equity Mutual Fund A,Maturity amount,Unknown,SIP Redemption,113376.0,Income,2018-01-04,NaT,2018,January,1
661,Equity Mutual Fund D,Maturity amount,Unknown,SIP Redemption,106875.0,Income,2018-01-04,NaT,2018,January,1
866,Saving Bank account 1,Salary,Unknown,From workplace,78298.0,Income,2017-11-01,NaT,2017,November,4
2061,Saving Bank account 1,Salary,Unknown,From workplace,77335.0,Income,2015-12-31,16:56:24,2015,December,4
1997,Saving Bank account 1,Salary,Unknown,From workplace,70806.0,Income,2016-03-31,10:25:01,2016,March,1
2256,Saving Bank account 1,Salary,Unknown,From workplace,70806.0,Income,2015-03-31,13:00:05,2015,March,1
33,Saving Bank account 1,Salary,Unknown,From workplace,70255.0,Income,2018-08-31,09:27:28,2018,August,3
105,Saving Bank account 1,Salary,Unknown,From workplace,70255.0,Income,2018-07-31,09:05:17,2018,July,3
250,Saving Bank account 1,Salary,Unknown,From workplace,65134.0,Income,2018-05-31,08:47:33,2018,May,2
323,Saving Bank account 1,Salary,Unknown,From workplace,65134.0,Income,2018-04-29,09:36:56,2018,April,2

In [200]:
df['Category'].value_counts()

Category
Food                         906
Transportation               307
Household                    176
subscription                 143
Other                        126
Investment                   101
Health                        94
Family                        71
Apparel                       47
Salary                        43
Money transfer                43
Recurring Deposit             41
Gift                          30
Public Provident Fund         29
Equity Mutual Fund E          22
Beauty                        22
Gpay Reward                   21
Education                     18
Saving Bank account 1         17
maid                          17
Festivals                     16
Equity Mutual Fund A          14
Equity Mutual Fund F          13
Dividend earned on Shares     12
Interest                      12
Culture                       11
Small Cap fund 2              10
Small cap fund 1              10
Share Market                   8
Life Insurance                 7
Maturity amount                7
Petty cash                     6
Equity Mutual Fund C           6
Bonus                          6
Tourism                        5
Rent                           4
Cook                           4
Grooming                       4
Saving Bank account 2          3
water (jar /tanker)            3
Self-development               2
Tax refund                     2
garbage disposal               2
Documents                      2
Amazon pay cashback            2
scrap                          2
Fixed Deposit                  2
Social Life                    1
Equity Mutual Fund D           1
Equity Mutual Fund B           1
Name: count, dtype: int64

In [201]:
df['Subcategory'].value_counts().head(20)

Subcategory
Unknown                    629
Milk                       162
auto                       142
snacks                     115
Grocery                    113
Kirana                      83
Lunch                       68
Mobile Service Provider     66
Mutual fund                 64
Medicine                    61
Train                       55
Dinner                      55
Pocket money                49
Tea                         42
Ice cream                   36
Appliances                  29
breakfast                   29
fruits                      28
Eggs                        27
beverage                    27
Name: count, dtype: int64

In [202]:
daily = (
    df[df['Income/Expense']=='Expense']
    .groupby(['Year','Month Name','Date'])['Amount']
    .sum()
)

daily

Year  Month Name  Date
2015  April       2015-04-01       50.0
                  2015-04-02     5000.0
                  2015-04-04     1526.0
                  2015-04-05    10000.0
                  2015-04-06     1000.0
                                 ...
2018  September   2018-09-15      200.0
                  2018-09-16      251.0
                  2018-09-17       19.0
                  2018-09-19      199.0
                  2018-09-20       90.0
Name: Amount, Length: 854, dtype: float64

In [203]:
daily.to_excel('Daily_Expense_Report.xlsx')

In [204]:
subscription = (
    df[df['Category']=='subscription']
    .groupby('Subcategory')['Amount']
    .sum()
    .sort_values(ascending=False)
)

subscription

Subcategory
Edtech Course              63733.42
Mobile Service Provider    26650.00
Wifi Internet Service       8460.00
Tata Sky                    4066.00
Newspaper                   3101.00
Mahanagar Gas               2208.00
Netflix                     1492.00
Amazon Prime                1477.00
Hotstar                     1243.49
Cable TV                     783.00
Kindle unlimited             676.00
Audible                      398.00
OTT Platform                 300.00
Name: Amount, dtype: float64

In [205]:
investment = (
    df[df['Category']=='Investment']
    .groupby('Subcategory')['Amount']
    .sum()
)

investment

Subcategory
LIC                       33858.0
Mutual fund               64000.0
Public Provident Fund    150000.0
RD                        22000.0
Name: Amount, dtype: float64

In [206]:
festival = (
    df[df['Category']=='Festivals']
    .groupby('Subcategory')['Amount']
    .sum()
)

festival

Subcategory
Diwali           3279.0
Ganesh Pujan      612.0
Holi               20.0
Navratri         2000.0
Rakshabandhan    1000.0
Name: Amount, dtype: float64

# Data Cleaning Process

## 1. Initial Data Inspection

* Loaded the dataset and inspected its structure using `.head()`, `.info()`, and `.describe()`.
* Checked the number of rows and columns.
* Verified the data types of all features.

## 2. Removed Redundant Column

* Removed the **Currency** column because it contained only one unique value (`INR`).
* Since the column had no variability, it did not contribute to the analysis.

## 3. Explored Unique Values

* Examined the unique values of all categorical columns to better understand the dataset.
* This helped identify transaction categories, payment modes, income/expense types, and subcategories.
* It also helped detect inconsistent category names and understand the overall structure of the data.

## 4. Subscription Analysis

* Investigated transactions under the **Subscription** category.
* Identified all subscription services such as Netflix, Amazon Prime, Hotstar, Audible, etc.
* Calculated the total amount spent on each subscription service to understand recurring expenses.

## 5. Date Format Correction

* Discovered that the **Date** column contained mixed formats:

  * `dd/mm/yyyy`
  * `dd/mm/yyyy hh:mm:ss`
* This caused incorrect results when performing date-based operations.
* Split the original column into:

  * **Date** (transaction date)
  * **Time** (transaction timestamp)
* Transactions without timestamps retain `NaT` in the **Time** column.

## 6. Missing Value Treatment

* Analyzed missing values across all columns.
* Replaced missing values in the **Subcategory** column with `"Unknown"` instead of removing the records.
* Retained missing values in the **Time** column because many transactions originally contained only the transaction date.

## 7. Duplicate Record Assessment

* Checked the dataset for duplicate records.
* Identified **9 duplicate rows**.
* Reviewed the duplicate records before deciding whether to remove them, ensuring that genuine repeated transactions were not mistakenly deleted.

## 8. Data Consistency Checks

* Examined categorical values for inconsistencies in naming and capitalization.
* Standardized inconsistent values (for example, `train` → `Train`, `medicine` → `Medicine`, `makeup` → `Makeup`) to improve grouping and reporting accuracy.

## 9. Feature Engineering

Created additional time-based features from the **Date** column:

* **Year**
* **Month Name**
* **Quarter**

These features enable year-wise, monthly, and quarterly trend analysis.

## 10. Final Validation

Performed a final quality check by:

* Verifying data types.
* Reviewing missing values.
* Checking duplicate records.
* Validating unique categorical values.
* Ensuring the dataset was ready for Exploratory Data Analysis (EDA) and Power BI dashboard development.

# Key Insights from the Analysis

## Financial Overview

* Calculated the total income, total expenses, and overall net savings.
* Measured the savings rate to understand overall financial health.

## Spending by Category

* Identified the highest and lowest spending categories.
* Analyzed how expenses are distributed across different categories to understand spending priorities.

## Spending by Subcategory

* Performed a detailed analysis of spending at the subcategory level.
* Identified frequently occurring expense types and high-cost subcategories.

## Subscription Analysis

* Identified all recurring subscription services.
* Calculated the total amount spent on each subscription.
* Determined which subscription contributed the most to recurring expenses.

## Monthly Spending Trends

* Analyzed monthly expense patterns using the engineered **Year** and **Month Name** features.
* Identified months with unusually high or low spending.

## Daily Expense Analysis

* Aggregated expenses on a daily basis to observe day-to-day spending behavior.
* Created a daily expense summary for further visualization and reporting.

## Payment Mode Analysis

* Examined how transactions were distributed across different payment methods such as Cash, Debit Card, Credit Card, and Bank Accounts.
* Identified the most frequently used payment mode.

## Transaction Analysis

* Calculated:

  * Average transaction amount
  * Largest expense transaction
  * Largest income transaction
* Used these metrics to better understand transaction behavior and detect unusually large transactions.

## Data Quality Insights

* Detected missing values and duplicate records.
* Identified inconsistencies in categorical values and standardized them to improve analytical accuracy.
* Preserved records with missing subcategories by assigning them to an **Unknown** category instead of removing them.

## Time-Based Analysis

* Leveraged the engineered **Year**, **Month Name**, and **Quarter** features to enable temporal analysis of financial transactions.
* Prepared the dataset for future trend analysis and interactive Power BI visualizations.

## Business Value

This analysis provides a comprehensive understanding of personal financial behavior by:

* Highlighting major spending areas.
* Tracking recurring subscription costs.
* Monitoring monthly spending patterns.
* Understanding payment preferences.
* Supporting informed budgeting and financial planning.
* Delivering a clean, analysis-ready dataset suitable for dashboard creation in Power BI.

# Next Steps

The cleaned dataset and derived analytical outputs are prepared for further reporting and visualization.

The next phase of the project includes:

* Exporting aggregated datasets (generated using `groupby()` operations and KPI calculations) into CSV/Excel format.
* Using these summarized datasets for deeper analysis and reporting.
* Building interactive Power BI dashboards using both the cleaned dataset and the aggregated reports.
* Creating KPI cards to display key metrics such as Total Income, Total Expenses, Net Savings, Savings Rate, and Average Transaction Amount.
* Designing visualizations for category-wise spending, monthly trends, subscription expenses, payment mode analysis, and daily expense patterns.
* Developing interactive dashboards with filters and slicers (Year, Month, Category, Income/Expense, Payment Mode, etc.) to enable dynamic exploration of financial data.
* Converting analytical findings into business insights that support budgeting, expense tracking, and financial decision-making.
* Preparing a professional reporting workflow where the exported Excel/CSV files can be shared with stakeholders or reused for future analysis without re-running the entire data processing pipeline.